import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const launcher = readFileSync('src/main/Launcher.ts', 'utf8')
const application = readFileSync('src/main/Application.ts', 'utf8')
const configManager = readFileSync('src/main/core/ConfigManager.ts', 'utf8')
const ipcHandler = readFileSync('src/main/core/IPCHandler.ts', 'utf8')

assert.match(launcher, /await application\.init\(\)/)
assert.match(application, /new LanguageRepository/)
assert.match(application, /new LanguageCoordinator/)
assert.match(application, /async init\(\)/)
assert.doesNotMatch(configManager, /AppI18n/)
assert.match(ipcHandler, /application:language-bootstrap/)
assert.match(ipcHandler, /application:language-prepare/)
assert.match(ipcHandler, /application:language-commit/)
assert.match(ipcHandler, /application:language-list-custom/)
assert.match(ipcHandler, /application:language-init-custom/)
const appNodeFn = readFileSync('src/main/core/AppNodeFn.ts', 'utf8')
assert.doesNotMatch(appNodeFn, /import ZH from '@lang\/zh'/)
assert.doesNotMatch(appNodeFn, /import EN from '@lang\/en'/)
const langPicker = readFileSync('src/render/components/Setup/LangSet/index.vue', 'utf8')
assert.match(langPicker, /onMounted/)
assert.match(langPicker, /LangSetup\.doLoad/)
console.log('language main integration tests passed')
