import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const read = (path: string) => readFileSync(join(root, path), 'utf-8')

const store = read('src/render/components/Neo4j/store.ts')
const controller = read('src/render/components/Neo4j/controller.ts')
const fork = read('src/fork/module/Neo4j/index.ts')
const index = read('src/render/components/Neo4j/Index.vue')
const aside = read('src/render/components/Neo4j/aside.vue')
const config = read('src/render/components/Neo4j/Config.vue')
const logs = read('src/render/components/Neo4j/Logs.vue')
const service = read('src/render/components/ServiceManager/index.vue')
const appTypes = read('src/shared/app.d.ts')
const brewTypes = read('src/render/store/brew.ts')
const installedTypes = read('src/render/core/Module/ModuleInstalledItem.ts')

assert.match(store, /export class Neo4jJavaBindingManager\b/)
assert.match(store, /reactiveBind\(new Neo4jJavaBindingManager\(/)
assert.match(store, /StorageGetAsync/)
assert.match(store, /StorageSetAsync/)
assert.doesNotMatch(store, /defineStore\(/)
assert.doesNotMatch(store, /from ['"]@\/store\/app['"]/)
assert.doesNotMatch(store, /neo4jJavaBindings/)
assert.match(store, /getBinding\(/)
const getBindingBody = store.match(
  /getBinding\([^)]*\): Neo4jJavaBinding \| undefined \{([\s\S]*?)\n\s{2}\}\n\n\s{2}async setBinding/
)
assert.ok(getBindingBody, 'getBinding implementation must be found')
assert.doesNotMatch(
  getBindingBody[1],
  /ensureHydrated|Object\.assign|this\.javaByBin\s*=/,
  'getBinding must stay read-only because it is called from the table render path'
)
assert.match(store, /setBinding\(/)
assert.match(store, /reconcileBindings\(/)
assert.match(store, /mutationQueue/)
assert.match(store, /import \{ watch \} from 'vue'/)
assert.match(store, /watchInstalledVersions\(\)/)
assert.match(store, /private installedVersionsWatching = false/)
assert.match(store, /if \(this\.installedVersionsWatching\) return/)
assert.match(store, /this\.reconcileBindings\(neo4jModule\.installed\)\.catch\(\(\) => undefined\)/)
assert.match(store, /sortJavaCandidatesByVersion/)
assert.match(controller, /export class Neo4jController\b/)
assert.match(controller, /readonly opening = ref\(false\)/)
assert.match(controller, /sendSensitive/)
assert.match(controller, /export default new Neo4jController\(\)/)
assert.doesNotMatch(controller, /startInternal|stopInternal|stopOtherVersions/)
assert.doesNotMatch(controller, /initialPassword/)
assert.doesNotMatch(controller, /neo4jNeedsPassword/)
assert.doesNotMatch(controller, /ElMessageBox\.prompt/)
assert.doesNotMatch(fork, /setInitialPassword/)
assert.doesNotMatch(fork, /set-initial-password/)
assert.doesNotMatch(fork, /password\?: string/)
assert.doesNotMatch(appTypes, /neo4jNeedsPassword/)
assert.doesNotMatch(brewTypes, /neo4jNeedsPassword/)
assert.doesNotMatch(installedTypes, /neo4jNeedsPassword/)
assert.doesNotMatch(appTypes, /javaHome\?|javaMajor\?|neo4jInstanceDir\?/)
assert.doesNotMatch(brewTypes, /javaHome\?|javaMajor\?|neo4jInstanceDir\?/)
assert.doesNotMatch(installedTypes, /javaHome\?|javaMajor\?|neo4jInstanceDir\?/)
assert.match(index, /<template #column="\{ row \}">/)
assert.match(index, /candidatesForVersion/)
assert.match(index, /Neo4jManager\.init\(\)/)
assert.doesNotMatch(index, /neo4jManager\.reconcileBindings\(/)
assert.doesNotMatch(index, /watch\(/)
assert.match(index, /:column-width="220"/)
assert.match(index, /style="color: #01cc74"/)
assert.match(index, /<Logs v-else-if="tab === 3" \/>/)
assert.doesNotMatch(index, /type="out"/)
assert.doesNotMatch(index, /type="error"/)
assert.doesNotMatch(index, /neo4jStore/)
assert.doesNotMatch(index, /from\s+['"]@\/util\/IPC['"]/)
assert.match(config, /initConfig/)
assert.match(config, /Neo4jManager\.instanceDirFor/)
assert.match(logs, /getLogFiles/)
assert.match(logs, /Neo4jManager\.instanceDirFor/)
assert.doesNotMatch(logs, /defineProps<\{ type: 'out' \| 'error' \}>/)
assert.doesNotMatch(logs, /props\.type/)
assert.match(service, /<slot name="column" :row="scope\.row">/)
assert.match(aside, /Neo4jManager\.watchInstalledVersions\(\)/)

console.log('Neo4j renderer tests passed')
