import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const setup = await readFile('src/render/components/Setup/Index.vue', 'utf8')
const aside = await readFile('src/render/components/Aside/Index.vue', 'utf8')
const mailpitPluginIndex = await readFile('plugins/mailpit/render/Index.vue', 'utf8')
const mailpitPluginAside = await readFile('plugins/mailpit/render/aside.vue', 'utf8')
const pluginPage = await readFile('src/render/components/Setup/Plugins/index.vue', 'utf8').catch(
  () => ''
)
const controller = await readFile('src/render/components/Setup/Plugins/controller.ts', 'utf8')
const ipc = await readFile('src/main/core/IPCHandler.ts', 'utf8')
assert.match(setup, /Plugins/)
assert.ok(setup.indexOf("value: 'plugins'") > setup.indexOf("value: 'about'"))
assert.doesNotMatch(aside, /pluginsTitle|navPluginMarket/)
assert.match(mailpitPluginIndex, /flyenv:mailpit/)
assert.match(mailpitPluginAside, /flyenv:mailpit-aside/)
assert.ok(pluginPage.length > 0)
assert.match(pluginPage, /third-party/i)
assert.match(pluginPage, /thirdParty/)
assert.match(pluginPage, /acknowledge/i)
assert.doesNotMatch(pluginPage, /const request =/)
assert.match(controller, /PluginMarketController/)
assert.match(controller, /busyById/)
assert.match(controller, /restartRequired/)
assert.match(controller, /third-party/i)
assert.match(controller, /application:plugin-market-list/)
assert.match(controller, /application:plugin-install/)
assert.match(controller, /application:plugin-uninstall/)
assert.match(controller, /comparePluginVersions/)
assert.match(controller, /reinstall/)
assert.match(controller, /inFlight/)
assert.match(controller, /return existing/)
assert.match(controller, /IPC\.off\(call\.key\)/)
assert.match(controller, /setTimeout/)
assert.match(ipc, /application:plugin-source-add/)
assert.match(ipc, /application:plugin-toggle/)
console.log('plugin market UI test passed')
